version: '3.8'

services:
  db:
    image: postgres:13.1
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sayang